#------------------------------------------------------------------------------
# Copyright: Wilde Consulting
#   License: Apache 2.0
#
# DESCRIPTION:
#		uvicorn log configuration file.
#
# VERSION INFO:
#      $Repo: fastapi_mongo
#    $Author: Anders Wiklund
#      $Date: 2023-03-03 00:57:54
#       $Rev: 65
#------------------------------------------------------------------------------

version: '3.7'

services:

  api:
    build:
      context: .
      args:
        BUILD_ENV: prod
    container_name: fastapi_mongo_example
    command: [gunicorn, -w=4, -k=uvicorn.workers.UvicornWorker, -b=:7000,
              --log-config=gunicorn.conf, --worker-tmp-dir=/dev/shm, src.main:app]
    restart: always
    ports:
      - "8100:7000"
    secrets:
      - mongo_url
      - service_pwd
    networks:
      - service_net

secrets:
    mongo_url:
      file: C:/Users/ander/AppData/Roaming/Python/secrets/mongo_prod_url
    service_pwd:
      file: C:/Users/ander/AppData/Roaming/Python/secrets/service_pwd

networks:
  service_net:
    name: custom_network
