#------------------------------------------------------------------------------
# Copyright: Wilde Consulting
#   License: Apache 2.0
#
# DESCRIPTION:
#		uvicorn log configuration file.
#
# VERSION INFO:
#      $Repo: fastapi_mongo
#    $Author: Anders Wiklund
#      $Date: 2023-03-04 20:12:53
#       $Rev: 71
#------------------------------------------------------------------------------

version: '3.7'

services:

  api:
    build:
      context: .
      args:
        BUILD_ENV: local
    container_name: fastapi_mongo_example
    command: [uvicorn, --reload, --host=0.0.0.0, --port=7000,
              --log-config=uvicorn.json, src.main:app]
    volumes:
      - ./part9/src/:/home/app/src/
    ports:
      - "8100:7000"
    secrets:
      - mongo_url
      - service_pwd
    networks:
      - service_net

secrets:
    service_pwd:
      file: C:/Users/ander/AppData/Roaming/Python/secrets/service_pwd
    mongo_url:
      file: C:/Users/ander/AppData/Roaming/Python/secrets/mongo_local_url

networks:
  service_net:
    name: custom_network
