#------------------------------------------------------------------------------
# Copyright: Wilde Consulting
#   License: Apache 2.0
#
# DESCRIPTION:
#		Docker-compose prod file.
#
# VERSION INFO:
#      $Repo: fastapi_mongo
#    $Author: Anders Wiklund
#      $Date: 2024-03-27 05:38:56
#       $Rev: 1
#------------------------------------------------------------------------------

version: '3.7'
name: fastapi_mongo

services:

  api:
    build:
      context: .
      args:
        BUILD_ENV: prod
    container_name: fastapi_mongo_example
    command: [ gunicorn, -w=4, -k=uvicorn.workers.UvicornWorker, -b=:7000,
               --log-config=gunicorn.conf, --worker-tmp-dir=/dev/shm, src.main:app ]
    restart: always
    ports:
      - "8100:7000"
    secrets:
      - mongo_url_prod
      - service_api_key
    environment:
      - ENVIRONMENT=prod
    networks:
      - service_net

secrets:
  mongo_url_prod:
    file: C:/Users/ander/AppData/Roaming/Python/secrets/mongo_url_prod
  service_api_key:
    file: C:/Users/ander/AppData/Roaming/Python/secrets/service_api_key

networks:
  service_net:
    external: true
    name: custom_network
